services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://todo_user:todo_pass@db:5432/todo_db?schema=public"
    ports:
      - "4000:4000"
    command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  postgres_data:
