
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://todo_user:todo_pass@db:5432/todo_db?schema=public"
      NODE_ENV: development
    ports:
      - "4000:4000"
    command: sh -c "
      echo '⏳ Waiting for db...';
      until pg_isready -h db -p 5432 -U todo_user; do sleep 2; done;
      echo '✅ Database ready, running migrations...';
      npx prisma migrate deploy;
      echo '🚀 Starting backend server...';
      npm run dev"

  frontend:
    build:
      context: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://localhost:4000"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

volumes:
  postgres_data:
